# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [17]:
import numpy as np

2. Create a null vector of size 10 

In [86]:
A=np.zeros(10)
print(A)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [69]:
a=np.arange(10,50)
(a)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [70]:
a = np.shape([0, 1, 2, 3])
a

(4,)

5. Print the type of the previous array in question 3

In [71]:
a = np.shape([0, 1, 2, 3])
a

(4,)

6. Print the numpy version and the configuration


In [74]:
print(np.version.version)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda\\Library\\include']
None


7. Print the dimension of the array in question 3


In [80]:
print(a)
np.ndim

[[1 2 3 5]
 [1 2 3 4]]


<function numpy.ndim(a)>

8. Create a boolean array with all the True values

In [77]:
A = np.array([4, 4, 4, 4, 4, 4])

print(A == 4)

[ True  True  True  True  True  True]


9. Create a two dimensional array




In [79]:
a=np.array([[1,2,3,5],[1,2,3,4]])
a

array([[1, 2, 3, 5],
       [1, 2, 3, 4]])

10. Create a three dimensional array



In [81]:
a=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
a

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [84]:
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [85]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [87]:
A=np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [88]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = np.array([1, 2, 3, 4, 5])*1.0
print(arr.dtype)

int32
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [89]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [90]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr=arr1==arr2
arr

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [91]:
arr=np.arange(0,10,3)
arr

array([0, 3, 6, 9])

18. Replace all odd numbers to -1 from previous array

In [92]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [93]:
na=np.arange(0,15)
na[5]=12
na[6]=12
na[7]=12
na[8]=12
na

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9, 10, 11, 12, 13, 14])

20. Create a 2d array with 1 on the border and 0 inside

In [94]:
ar_2d=np.eye(4,4)
ar_2d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [95]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [96]:
arr3d = np.array([[[1, 2, 3*64.0], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64., 64., 64.],
        [64., 64., 64.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [97]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0][0:5]

6

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [99]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [100]:
t_d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(t_d)
print('\n',t_d[:2:,3])

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [3 8]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [102]:
Z=np.random.random((10,10))
Zmin, Zmax=Z.min(), Z.max()
print(Zmin, Zmax)

0.004973897699328322 0.999399906960649


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [103]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.unique((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [104]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b,a,b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


NameError: name 'names' is not defined

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [5]:
names

NameError: name 'names' is not defined

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [7]:
rand_arr = np.random.randint(low=1, high=15, size=(5,3)) + np.random.random((5,3))

rand_arr = np.random.uniform(1,15, size=(5,3))


NameError: name 'np' is not defined

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [130]:
b=np.array([[[1,2,3,4],[5,6,7,8]]])
b
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

33. Swap axes of the array you created in Question 32

In [23]:
arr = np.arrange(10).reshape((5 , 2))
arr = np.(32)

SyntaxError: invalid syntax (<ipython-input-23-306c1d9e1f5b>, line 2)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [133]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [132]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [131]:
r=np.random.randn(20)
print(r)
print('\n',r.cumsum())

[-0.39043499 -0.21365915 -0.48794872 -0.2280954   1.78569674  0.776334
  0.87957501 -0.46970515  0.83098913  0.78543351  0.21417109 -1.71752782
  0.66044064 -0.48404149 -0.17796186 -1.23567802 -0.31573309  0.74321543
 -1.45646215 -1.1776407 ]

 [-0.39043499 -0.60409415 -1.09204287 -1.32013827  0.46555847  1.24189247
  2.12146748  1.65176233  2.48275147  3.26818498  3.48235608  1.76482826
  2.42526889  1.94122741  1.76326555  0.52758753  0.21185445  0.95506988
 -0.50139227 -1.67903297]
